exp_dir: "experiments/e4e/ffhq_e4e_r50"
output_dir: './inference_result/restyle'

# Data
train_dataset_path: './data/FFHQ'
test_dataset_path: './data/CelebA-HQ/test'

# Hyper-parameter of training
checkpoint_path: 'pretrained_models/restyle/restyle-e4e_ffhq_r50_wp_official.pt'
stylegan_weights: "pretrained_models/stylegan2-ffhq-config-f.pt"
batch_size: 8
workers: 8
test_batch_size: 8
test_workers: 8
start_from_latent_avg: False
encoder_type: ProgressiveBackboneEncoder

# Image Loss
lpips_lambda: 0.8
id_lambda: 0.1
l2_lambda: 1.0
w_norm_lambda: 0.
delta_norm_lambda: 2e-4

# Discriminator
w_discriminator_lambda: 0.1
r1: 10
use_w_pool: True

# Progressive Training
progressive_start: 20000
progressive_step_every: 2000

# Wandb
#use_wandb: True
wandb_project: ffhq-inversion