embed_mode: 'encoder'
refine_mode: 'hfgi'
test_dataset_path: "./data/CelebA-HQ/test"
test_batch_size: 1
output_dir: './inference_result/hfgi'
checkpoint_path: "pretrained_models/hfgi/hfgi_ffhq_official.pt"