embed_mode: 'encoder'
refine_mode: 'hyperstyle'
test_dataset_path: "./data/CelebA-HQ/test"
test_batch_size: 1
output_dir: './inference_result/hyperstyle'
hyperstyle_iteration: 5
hypernet_checkpoint_path: "pretrained_models/hyperstyle/hyperstyle_ffhq_official.pt"