refine_mode: 'pti'
test_dataset_path: './data/CelebA-HQ/test'
test_batch_size: 1
stylegan_weights: "pretrained_models/stylegan2-ffhq-config-f.pt"
output_dir: './inference_result/pti'

# PTI options
pti_lr: 3e-4
pti_step: 350
pti_l2_lambda: 1.
pti_lpips_lambda: 1.
pti_regulizer_lambda: 1.
pti_regulizer_l2_lambda': 0.1
pti_r_lpips_lambda': 0.1
pti_locality_regularization_interval: 50
pti_regulizer_alpha: 30.
pti_latent_ball_num_of_samples: 1